[build]
command = "pnpm run build"
publish = ".next"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
NODE_VERSION = "18"
NEXT_PUBLIC_SITE_URL = "https://hogis-ordernow.netlify.app"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
node_bundler = "esbuild"