[build]
  command = "npm run build"
  publish = ".next"

# Environment variables
[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_EDGE_IMAGES = "true"
  NODE_VERSION = "18"
  NEXT_PUBLIC_SITE_URL = "https://hogis-ordernow.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"